name: docker-build

on: 
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request_target:
    branches: ["main"]

env:
  IMAGE_NAME: christiandupuis299/frontend
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}
  DOCKERFILE_PATH: Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SHA }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Log into registry
        uses: docker/login-action@v2.1.0
        with:
          username: christiandupuis299
          password: ${{ secrets.HUB_PAT }}
          
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
             #type=raw,latest
             type=sha,prefix=,suffix=,format=short
          labels: |
            org.opencontainers.image.revision=${{ env.SHA }}
            com.docker.image.source.entrypoint=${{ env.DOCKERFILE_PATH }}

      - name: Build and push Docker image on push
        id: build-and-push
        #if: ${{ github.event_name != 'pull_request_target' }}
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: "linux/amd64,linux/arm64"
          attests: type=sbom,generator=docker/scout-sbom-indexer:1
          provenance: true
          
      - name: Analyze image
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: docker/scout-action@main
        with:
          command: cves,policy
          image: ${{ steps.meta.outputs.tags }}
          platform: "linux/arm64"
          summary: true
          organization: christiandupuis299
      
      - name: Compare to deployed image
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: docker/scout-action@main
        with:
          command: compare
          image: ${{ steps.meta.outputs.tags }}
          only-severities: critical,high
          to-stream: prod
          platform: "linux/arm64"
          exit-code: true       
          summary: true
          organization: christiandupuis299

