name: docker-build

on: 
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request_target:
    branches: ["main"]

env:
  IMAGE_NAME: christiandupuis299/frontend
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}
  DOCKERFILE_PATH: Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SHA }}

      - name: Witness Run
        uses: testifysec/witness-run-action@v0.1.5
        with:
          step: build
          enable-archivista: false
          enable-sigstore: false
          outfile: witness.json
          command: ls -la

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          username: christiandupuis299
          password: ${{ secrets.HUB_PAT }}
          
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.revision=${{ env.SHA }}
            com.docker.image.source.entrypoint=${{ env.DOCKERFILE_PATH }}

      - name: Build and push Docker image on push
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: "linux/amd64,linux/arm64"
          attests: type=sbom,generator=docker/scout-sbom-indexer:1
          provenance: true       

      - name: Secret Scanning
        id: trivy-secret-scanning
        uses: aquasecurity/trivy-action@0.19.0
        with:
          image-ref: ${{ steps.meta.outputs.tags }}
          format: json
          output: secret-scanning.json
          scanners: secret

      - name: Attach Secret Scanning report
        run: |
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --
          docker scout attestation add ${{ steps.meta.outputs.tags }} --file secret-scanning.json --predicate-type https://aquasecurity.com/trivy/v2