name: sast

on: 
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request_target:
    branches: ["main"]

env:
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}
  DOCKERFILE_PATH: Dockerfile

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SHA }}
    
      - name: MegaLinter
        uses: oxsecurity/megalinter@v7
        id: ml
        # All available variables are described in documentation
        # https://megalinter.io/configuration/
        env:
          VALIDATE_ALL_CODEBASE: >-
            ${{
              github.event_name == 'push' &&
              contains(fromJSON('["refs/heads/main", "refs/heads/master"]'), github.ref)
            }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SARIF_REPORTER: true
          DISABLE_ERRORS: true

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ env.DOCKERFILE_PATH }}
          format: sarif
          output-file: hadolint.sarif.json
          no-fail: true

      - name: Log into registry
        uses: docker/login-action@v3.0.0
        with:
          username: christiandupuis299
          password: ${{ secrets.HUB_PAT }}          
  
      - name: Upload SARIF results #1
        uses: docker/scout-action@sarif
        with:
          command: sarif-upload
          organization: christiandupuis299
          sarif-file: megalinter-reports/megalinter-report.sarif
          
      - name: Upload SARIF results #2
        uses: docker/scout-action@sarif
        with:
          command: sarif-upload
          organization: christiandupuis299
          sarif-file: hadolint.sarif.json
