name: Release docker image

on:
  push:
    #branches:
    #  - 'main'
    tags:
      # Publish semver tags as releases.
      - 'v*.*.*' # ${{  github.ref_name }}
  workflow_dispatch:
    inputs:
      push:
        description: "Push the image"
        required: true
        type: boolean

  #pull_request:
  #  branches:
  #    - 'main'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: docker/scout-cli
  # SHA: ${{ github.event.pull_request.head.sha || github.event.after }}
  DOCKERFILE_PATH: Dockerfile
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  PLATFORMS: "linux/386,linux/amd64,linux/arm64,linux/arm/v5,linux/arm/v7,linux/ppc64le,linux/riscv64,linux/s390x"
  SHA: ${{ github.event.pull_request.head.sha || github.event.after || github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Attach vex document
        run: |
          echo docker scout attestation add ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$(echo ${{ env.SHA}} | head -c 7) --file .vex/docker-scout.vex.json --predicate-type https://openvex.dev/ns/v0.2.0
